setup/urls.py
from django.urls import path
from django.conf.urls.static import static
from setup import settings

from playlist.views import MusicaCreateView, MusicaDeleteView, MusicaDetailView, MusicaListView, MusicaUpdateView, PlaylistCreateView, PlaylistDeleteView, PlaylistDetailView, PlaylistListView, PlaylistUpdateView

urlpatterns = [
    path('', PlaylistListView.as_view(), name='playlist_list'),
    path('create/', PlaylistCreateView.as_view(), name='playlist_create'),
    path('<int:pk>/', PlaylistDetailView.as_view(), name='playlist_detail'),
    path('<int:pk>/edit/', PlaylistUpdateView.as_view(), name='playlist_update'),
    path('<int:pk>/delete/', PlaylistDeleteView.as_view(), name='playlist_delete'),

    path('musicas/', MusicaListView.as_view(), name='musica_list'),
    path('musicas/<int:pk>/', MusicaDetailView.as_view(), name='musica_detail'),
    path('musicas/create/', MusicaCreateView.as_view(), name='musica_create'),
    path('musicas/<int:pk>/edit/', MusicaUpdateView.as_view(), name='musica_update'),
    path('musicas/<int:pk>/delete/', MusicaDeleteView.as_view(), name='musica_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

playlist/models.py
from django.db import models
from django.core.validators import FileExtensionValidator

class Musica(models.Model):
    titulo = models.CharField(max_length=100)
    artista = models.CharField(max_length=100)
    album = models.CharField(max_length=100,blank=True)
    capa = models.ImageField(upload_to='capas/', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])

    def __str__(self):
        return f"{self.titulo} {self.artista}"

class Playlist(models.Model):
    nome = models.CharField(max_length=100)
    musicas = models.ManyToManyField(Musica) 

    def __str__(self):
        return self.nome

playlist/forms.py
from django import forms
from .models import Playlist, Musica

class PlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = '__all__'

class MusicaForm(forms.ModelForm):
    class Meta:
        model = Musica
        fields = '__all__'

playlist/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from playlist.forms import MusicaForm, PlaylistForm
from playlist.models import Musica, Playlist 

class PlaylistListView(ListView):
    model = Playlist
    template_name = 'playlist/playlist_list.html'
    context_object_name = 'playlists'
    paginate_by = 8
    queryset = Playlist.objects.order_by('-id')

class PlaylistDetailView(DetailView):
    model = Playlist
    context_object_name = 'playlists'
    template_name = 'playlist/playlist_detail.html'

class PlaylistCreateView(CreateView):
    model = Playlist
    form_class = PlaylistForm
    template_name = 'playlist/playlist_form.html'
    success_url = reverse_lazy('playlist_list')

class PlaylistUpdateView(UpdateView):
    model = Playlist
    fields = ['nome', 'musicas']  
    template_name = 'playlist/playlist_form.html'
    success_url = reverse_lazy('playlist_list')  

class PlaylistDeleteView(DeleteView):
    model = Playlist
    context_object_name = 'playlists'
    success_url = reverse_lazy('playlist_list')  

# musicas crud

class MusicaListView(ListView):
    model = Musica
    template_name = 'musicas/musica_list.html'

class MusicaDetailView(DetailView):
    model = Musica
    template_name = 'musicas/musica_detail.html'

class MusicaCreateView(CreateView):
    model = Musica
    form_class = MusicaForm
    template_name = 'musicas/musica_form.html'
    success_url = reverse_lazy('musica_list')

class MusicaUpdateView(UpdateView):
    model = Musica
    form_class = MusicaForm
    template_name = 'musicas/musica_form.html'
    success_url = reverse_lazy('musica_list')  

class MusicaDeleteView(DeleteView):
    model = Musica
    template_name = 'musicas/musica_confirm_delete.html'
    success_url = reverse_lazy('musica_list')

playlist/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load bootstrap5 %}
    {% load static %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Meu Projeto de Playlists</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'playlist_list' %}">Playlists</a>
                    </li>
                    <li> <a class="nav-link active" aria-current="page" href="{% url 'musica_list' %}">Musicas</a></li>
                    </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


</body>
</html>

playlist/templates/musicas/musica_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Confirmar Exclusão</h1>
<p>Tem certeza que deseja excluir a playlist "{{ object.nome }}"?</p>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Sim">
    <a href="{% url 'playlist_detail' object.pk %}">Não</a>
</form>

{% endblock %}

playlist/templates/musicas/musica_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ object.titulo }}</h2>
<p>Artista: {{ object.artista }}</p>
<p>Álbum: {{ object.album }}</p>
<p>Playlists:
    {% for playlist in object.playlist_set.all %}
        {{ playlist.nome }}
    {% endfor %}
</p>

{% endblock %}

playlist/templates/musicas/musica_form.html
{% extends 'base.html' %}

{% block content %}

<h1>{% if form.instance.pk %}Editar{% else %}Criar{% endif %} Música</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
</form>

{% endblock %}

playlist/templates/musicas/musica_list.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'musica_create' %}" class="btn btn-primary mb-3">Criar Música</a>

<ul>
    {% for musica in object_list %}
        <li>{{ musica.titulo }} - {{ musica.artista }}
            <img src="{{ musica.capa.url }}" alt="{{ musica.titulo }}" width=100>
            <a href="{% url 'musica_detail' musica.pk %}" class="btn btn-primary">Detalhes</a>
            <a href="{% url 'musica_update' musica.pk %}" class="btn btn-secondary">Editar</a>
            <a href="{% url 'musica_delete' musica.pk %}" class="btn btn-danger">Excluir</a>
        </li>
    {% endfor %}
</ul>



{% endblock %}

playlist/templates/playlist/playlist_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Confirmar Exclusão</h1>
<p>Tem certeza que deseja excluir a playlist "{{ playlists.nome }}"?</p>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Sim">
    <a href="{% url 'playlist_detail' playlists.pk %}">Não</a>
</form>
{% endblock %}

playlist/templates/playlist/playlist_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ playlists.nome }}</h2>
<ul>
    {% for musica in playlists.musicas.all %}
    <li>{{ musica.titulo }} - {{ musica.artista }} - <img src="{{ musica.capa.url }}" alt="{{ musica.titulo }}" width=100></li>
    {% endfor %}
</ul>
<a href="{% url 'playlist_update' playlists.pk %}">Editar</a>
<a href="{% url 'playlist_delete' playlists.pk %}">Excluir</a>

{% endblock %}

playlist/templates/playlist/playlist_form.html
{% extends 'base.html' %}

{% block content %}

<h1>{% if form.instance.pk %}Editar{% else %}Criar{% endif %} Playlist</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
</form>

{% endblock %}

playlist/templates/playlist/playlist_list.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'playlist_create' %}" class="btn btn-primary mb-3">Criar Playlist</a>


{% for playlist in playlists %}
<li>
    {{ playlist.nome }}
    
    <a href="{% url 'playlist_detail' playlist.pk %}">Detalhes</a>
    <a href="{% url 'playlist_update' playlist.pk %}">Editar</a>
    <a href="{% url 'playlist_delete' playlist.pk %}">Excluir</a>
</li>

{% endfor %}
</ul>

<!-- Paginação -->
<nav aria-label="Navegação de páginas">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="Primeira">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Anterior">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">&laquo;&laquo;</span></li>
            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
        {% endif %}

        <li class="page-item active">
            <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Próxima">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Última">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
            <li class="page-item disabled"><span class="page-link">&raquo;&raquo;</span></li>
        {% endif %}
    </ul>
</nav>
</div>
{% endblock %}